version: '3.8'

volumes:
    acme:
    certs:
    html:
    grafana:
    prometheus:

networks:
    host_network:
        name: proxy-network
        driver: bridge

services:
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        restart: unless-stopped
        networks:
            - default
            - host_network
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - DEFAULT_HOST=luxoft.local

    acme-companion:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        restart: unless-stopped
        environment:
            - DEFAULT_EMAIL=${DEFAULT_EMAIL:-admin@luxoft.local}
        volumes_from:
            - nginx-proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro

    whoami:
        container_name: whoami
        image: jwilder/whoami
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=whoami.local

    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter:latest
        restart: unless-stopped
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        ports:
            - 9100:9100

    grafana:
        container_name: grafana
        image: grafana/grafana-enterprise
        restart: unless-stopped
        volumes:
            - grafana:/var/lib/grafana
        ports:
            - 3000:3000

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        restart: unless-stopped
        mem_limit: 6000m
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/prometheus/users.yml:/etc/prometheus/users.yml
            - prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
            - '--web.enable-admin-api'
        ports:
            - 9090:9090
